### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by joaoofreitas** [joaoofreitas/0xg0.st#1]
- [x]  Block certain malicious mime-types
- [x] Implement _Alder-32_ hashing for file  generation
- [x]  ~Add SQLite for saving hashes~
- [x]  Store all files inside a hashed directory
